"""New-paper onboarding helpers."""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path
from typing import Any


def init_paper_manifest(
    *,
    arxiv_id: str,
    repo_url: str,
    output_path: Path,
    commit: str | None = None,
    title: str | None = None,
) -> Path:
    """Create a draft ClaimManifest skeleton for a new paper."""

    paper_id = arxiv_id.replace(".", "_")
    manifest = _draft_manifest(
        paper_id=paper_id,
        arxiv_id=arxiv_id,
        repo_url=repo_url,
        commit=commit,
        title=title,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return output_path


def _draft_manifest(
    *,
    paper_id: str,
    arxiv_id: str,
    repo_url: str,
    commit: str | None,
    title: str | None,
) -> dict[str, Any]:
    return {
        "schema_version": "0.1.0",
        "paper": {
            "paper_id": paper_id,
            "title": title or "TODO: paper title",
            "arxiv_id": arxiv_id,
            "paper_url": f"https://arxiv.org/abs/{arxiv_id}",
            "repo_url": repo_url,
            "repo_commit": commit or "TODO: pin repository commit",
            "domain": "TODO: domain",
            "license": None,
            "hardware_profile": "TODO: cpu_or_gpu",
        },
        "claims": [
            {
                "claim_id": f"{paper_id}_claim_001",
                "text": "TODO: claim text from paper table or result section",
                "claim_type": "numeric_metric",
                "paper_location": "TODO: table/section/page",
                "evidence_snippet": "TODO: exact paper snippet supporting the claim",
                "expected_metric": {
                    "name": "TODO: metric name",
                    "value": "TODO: expected value",
                    "unit": None,
                    "higher_is_better": None,
                },
                "tolerance": {
                    "type": "manual",
                    "value": "TODO: tolerance",
                    "rationale": "TODO: why this tolerance is acceptable",
                },
                "linked_experiment_ids": [],
                "confidence": 0.0,
                "status": "unverified_candidate",
            }
        ],
        "experiments": [],
        "environment": {
            "execution_mode": "manual",
            "base_image": "TODO: base image",
            "python_version": "TODO: python version",
            "cuda_version": None,
            "dependency_files": [],
            "image_digest": None,
        },
        "datasets": [],
        "cached_runs": [],
        "provenance": {
            "created_by": "claimbench init-paper",
            "created_at": date.today().isoformat(),
            "extraction_model": None,
            "parser_version": None,
            "manual_edits": [],
            "review_status": "draft",
        },
        "validation": {
            "unresolved_fields": [
                "paper.title",
                "paper.repo_commit",
                "paper.domain",
                "claims[0]",
                "experiments",
                "environment",
                "datasets",
            ],
            "notes": "Draft manifest generated by onboarding. Review and resolve TODO fields before execution.",
        },
    }
